name: "Upload file to ftp(s) server"
description: "Upload file to ftp(s) server"
author: Kaven[kaven@wuwenkai.com]
branding:
  icon: "arrow-up-circle"
  color: "blue"
inputs:
  server:
    description: "server address"
    required: true
  port:
    description: "server port"
    required: true
    default: 21
  file:
    required: true
  username:
    required: true
  password:
    required: true
  cwd:
    default: ''
  rename-file-to:
    default: ""
  debug:
    default: false
  json_stringify_data:
    # '["file1","file2","..."]'
    default: '[]'

runs:
  using: "node12"
  main: "dist/index.js"
